### ISSUE TITLE
No package available

### ISSUE THREAD

**Issue by mblaettler** [MichaelWehar/Crossword-Layout-Generator#6]
Hi

Thanks for your cool script. It's exactly what I need for my personal project. Do you have any plans about releasing the package on [npmjs](https://npmjs.com)?

It would really simplify development and deployment.

Thanks in advance

Michael

**Comment by MichaelWehar** [comment]
Thank you so much for opening up this issue and for the kind comment!

I've never created a package on npmjs, but I think this is a good idea.  I'm down.  :)

If you're willing to share your personal project, we could list it in our ReadMe.

Regardless, it would be great to hear more about it.

Hope that you have a nice day!

**Comment by mblaettler** [comment]
If you need any support let me know. I'm glad to help you set up your package, so you only need to publish it.

I plan to add a crossword plugin for [editor.js](https://editorjs.io/). I think I'll open source the plugin as soon as it works.

**Comment by MichaelWehar** [comment]
That would be great!  If you setup the package, then I'll review it and submit it.  If you like, you can add the package to a new branch and do a pull request.

Also, adding the crossword plugin to editor.js sounds great!  I'm excited to see how it turns out.  :)

Thank you again!

**Comment by mblaettler** [comment]
Ok, I'll setup a package in the coming days and create a pull request.

**Comment by MichaelWehar** [comment]
Awesome!  Thank you very much.  :)

**Comment by MichaelWehar** [comment]
Still working on this.  :)

**Comment by mblaettler** [comment]
Looking forward to the package being available on npm. ;-)

Thank you for your work. In case you have questions or need additional support feel free to contact me again.

**Comment by MichaelWehar** [comment]
Package is now available!

Link: https://www.npmjs.com/package/crossword-layout-generator

Thank you again for all of your help!  :)
